In [28]:
import numpy as np
from warnings import warn

In [29]:
A = [[j * i if (j == i or j == i-1 or j == i +1) else 0 for j in range(1, 10) ]for i in range(1, 10)]

In [30]:
A = np.array(A)
A

array([[ 1,  2,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  4,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  9, 12,  0,  0,  0,  0,  0],
       [ 0,  0, 12, 16, 20,  0,  0,  0,  0],
       [ 0,  0,  0, 20, 25, 30,  0,  0,  0],
       [ 0,  0,  0,  0, 30, 36, 42,  0,  0],
       [ 0,  0,  0,  0,  0, 42, 49, 56,  0],
       [ 0,  0,  0,  0,  0,  0, 56, 64, 72],
       [ 0,  0,  0,  0,  0,  0,  0, 72, 81]])

In [31]:
def solve_tridiag(A: np.ndarray, b_vec: np.ndarray) -> np.ndarray:
    '''
    Resolve um sistema tridiagonal da forma Ax = d onde A é uma matriz triagonal
    '''
    n = len(A)
    a = np.array([A[i][i-1] for i in range(1, n)])
    b = np.array([A[i][i] for i in range(n)])
    c = np.array([A[i][i+1] for i in range(n-1)])

    d = np.array([i for i in b_vec], dtype= float) # cópia profunda do vetor b_vec

    x = np.zeros(n)

    try:
        c[0] = c[0] / b[0]
        d[0] = d[0] / b[0]
    except ZeroDivisionError:
        warn(f'Divisão por zero no índice 0 da matriz b')
        raise ZeroDivisionError
    
    
    for i in range(1, n-1):
        try:
            div = (b[i] - a[i-1] * c[i-1])
            c[i] = c[i] / div
            d[i] = (d[i] - (a[i-1] * d[i-1])) / div
            
        except ZeroDivisionError:
            warn(f'Divisão por zero no índice {i} da matriz b')
            raise ZeroDivisionError
    
    try:
        d[n-1] = (d[n-1] - (a[n-2] * d[n-2])) / (b[n-1] - a[n-2] * c[n-2])
    
    except ZeroDivisionError:
        warn(f'Divisão por zero no índice {i} da matriz b')
        raise ZeroDivisionError




    x[-1] = d[-1]

    for i in range(n-2, -1, -1):
        x[i] = d[i] - c[i] * x[i+1]
    
    return x

In [32]:
A = np.zeros((5, 5))

In [33]:
for i in range(5):
    for j in range(5):
        if i == j:
            A[i][j] = 2
        elif abs(i - j) == 1:
            A[i][j] = 1

In [34]:
A

array([[2., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [0., 1., 2., 1., 0.],
       [0., 0., 1., 2., 1.],
       [0., 0., 0., 1., 2.]])

In [35]:
result = np.array([4, 4, 0, 0, 2])

In [36]:
solve_tridiag(A, result)

array([ 1.00000000e+00,  2.00000000e+00, -1.00000000e+00, -3.33066907e-16,
        1.00000000e+00])

In [37]:
A = np.zeros((6, 6))

b = np.array([5, 3, 4, 2, 3, 2])
a = np.array([1, 2, 1, 2, 1])
c = np.array([4, 1, 1, 1, 2])

for i in range(6):
    for j in range(6):
        if i == j:
            A[i][j] = b[i]
        elif j - 1 == i:
            A[i][j] = c[i]
        elif i - 1 == j:
            A[i][j] = a[i-1]

In [38]:
A

array([[5., 4., 0., 0., 0., 0.],
       [1., 3., 1., 0., 0., 0.],
       [0., 2., 4., 1., 0., 0.],
       [0., 0., 1., 2., 1., 0.],
       [0., 0., 0., 2., 3., 2.],
       [0., 0., 0., 0., 1., 2.]])

In [39]:
result = np.array([13, 10, 20, 16, 35, 17])

In [40]:
result

array([13, 10, 20, 16, 35, 17])

In [41]:
solve_tridiag(A, result)

array([1., 2., 3., 4., 5., 6.])